steps:
    - name: 'hashicorp/terraform:1.8'
      dir: 'infrastructure/'
      entrypoint: 'sh'
      args:
      - '-c'
      - |-      
        # Init and Apply Terraform
        terraform init -backend-config=bucket=$_TF_STATE_BUCKET_NAME_
        terraform apply -parallelism=$_TF_PARALLELISM_ -var github-host-connection-name=$_GITHUB_HOST_CONNECTION_NAME_ -var github-repo-name=$_GITHUB_REPO_NAME_ -var project=$_PROJECT_ID_ -var region=$_REGION_ -var demo-name=$_DEMO_NAME_ -var tf-parallelism=$_TF_PARALLELISM_ -auto-approve
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 3600s